// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import {
  GetPlaceAdditionalFeature,
  ReverseGeocodeAdditionalFeature,
  SearchTextAdditionalFeature,
} from "@aws-sdk/client-geo-places";

export enum PlaceTypes {
  AddressType = "AddressType",
  StreetType = "StreetType",
  IntersectionType = "IntersectionType",
  PointOfInterestType = "PointOfInterestType",
  CountryType = "CountryType",
  RegionType = "RegionType",
  SubRegionType = "SubRegionType",
  MunicipalityType = "MunicipalityType",
  NeighborhoodType = "NeighborhoodType",
  PostalCodeType = "PostalCodeType",
}

export enum CategoriesEnum {
  Airport = "Airport",
  AmusementPark = "AmusementPark",
  Aquarium = "Aquarium",
  ArtGallery = "ArtGallery",
  ATM = "ATM",
  Bakery = "Bakery",
  Bank = "Bank",
  Bar = "Bar",
  BeautySalon = "BeautySalon",
  BusStation = "BusStation",
  CarDealer = "CarDealer",
  CarRental = "CarRental",
  CarRepair = "CarRepair",
  CarWash = "CarWash",
  Cemetery = "Cemetery",
  Cinema = "Cinema",
  CityHall = "CityHall",
  ClothingStore = "ClothingStore",
  CoffeeShop = "CoffeeShop",
  ConsumerElectronicsStore = "ConsumerElectronicsStore",
  ConvenienceStore = "ConvenienceStore",
  CourtHouse = "CourtHouse",
  Dentist = "Dentist",
  Embassy = "Embassy",
  FireStation = "FireStation",
  FitnessCenter = "FitnessCenter",
  GasStation = "GasStation",
  GovernmentOffice = "GovernmentOffice",
  Grocery = "Grocery",
  HigherEducation = "HigherEducation",
  Hospital = "Hospital",
  Hotel = "Hotel",
  Laundry = "Laundry",
  Library = "Library",
  LiquorStore = "LiquorStore",
  Lodging = "Lodging",
  Market = "Market",
  MedicalClinic = "MedicalClinic",
  Motel = "Motel",
  Museum = "Museum",
  Nightlife = "Nightlife",
  NursingHome = "NursingHome",
  Park = "Park",
  Parking = "Parking",
  PetStore = "Pet Store",
  Pharmacy = "Pharmacy",
  Plumbing = "Plumbing",
  PoliceStation = "PoliceStation",
  PostOffice = "PostOffice",
  ReligiousPlace = "ReligiousPlace",
  Restaurant = "Restaurant",
  School = "School",
  ShoppingMall = "ShoppingMall",
  SportsCenter = "SportsCenter",
  Storage = "Storage",
  TaxiStand = "TaxiStand",
  TouristAttraction = "TouristAttraction",
  TrainStation = "TrainStation",
  VeterinaryCare = "VeterinaryCare",
  Zoo = "Zoo",
}

export enum CountriesEnum {
  Afghanistan = "AFG",
  "Aland Islands" = "ALA",
  Albania = "ALB",
  Algeria = "DZA",
  "American Samoa" = "ASM",
  Andorra = "AND",
  Angola = "AGO",
  Anguilla = "AIA",
  Antarctica = "ATA",
  "Antigua and Barbuda" = "ATG",
  Argentina = "ARG",
  Armenia = "ARM",
  Aruba = "ABW",
  Australia = "AUS",
  Austria = "AUT",
  Azerbaijan = "AZE",
  Bahamas = "BHS",
  Bahrain = "BHR",
  Bangladesh = "BGD",
  Barbados = "BRB",
  Belarus = "BLR",
  Belgium = "BEL",
  Belize = "BLZ",
  Benin = "BEN",
  Bermuda = "BMU",
  Bhutan = "BTN",
  Bolivia = "BOL",
  "Bosnia and Herzegovina" = "BIH",
  Botswana = "BWA",
  "Bouvet Island" = "BVT",
  Brazil = "BRA",
  "British Indian Ocean Territory" = "IOT",
  "Brunei Darussalam" = "BRN",
  Bulgaria = "BGR",
  "Burkina Faso" = "BFA",
  Burundi = "BDI",
  Cambodia = "KHM",
  Cameroon = "CMR",
  Canada = "CAN",
  "Cape Verde" = "CPV",
  "Cayman Islands" = "CYM",
  "Central African Republic" = "CAF",
  Chad = "TCD",
  Chile = "CHL",
  China = "CHN",
  "Christmas Island" = "CXR",
  "Cocos Keeling Islands" = "CCK",
  Colombia = "COL",
  Comoros = "COM",
  "Congo" = "COG",
  "Congo Democratic Republic" = "COD",
  "Cook Islands" = "COK",
  "Costa Rica" = "CRI",
  "Cote D'Ivoire" = "CIV",
  Croatia = "HRV",
  Cuba = "CUB",
  Cyprus = "CYP",
  CzechRepublic = "CZE",
  Denmark = "DNK",
  Djibouti = "DJI",
  Dominica = "DMA",
  "Dominican Republic" = "DOM",
  Ecuador = "ECU",
  Egypt = "EGY",
  "El Salvador" = "SLV",
  "Equatorial Guinea" = "GNQ",
  Eritrea = "ERI",
  Estonia = "EST",
  Ethiopia = "ETH",
  "Falkland Islands" = "FLK",
  "Faroe Islands" = "FRO",
  Fiji = "FJI",
  Finland = "FIN",
  France = "FRA",
  "French Guiana" = "GUF",
  "French Polynesia" = "PYF",
  "French Southern Territories" = "ATF",
  Gabon = "GAB",
  Gambia = "GMB",
  Georgia = "GEO",
  Germany = "DEU",
  Ghana = "GHA",
  Gibraltar = "GIB",
  Greece = "GRC",
  Greenland = "GRL",
  Grenada = "GRD",
  Guadeloupe = "GLP",
  Guam = "GUM",
  Guatemala = "GTM",
  Guernsey = "GGY",
  Guinea = "GIN",
  "Guinea Bissau" = "GNB",
  Guyana = "GUY",
  Haiti = "HTI",
  "Heard Island Mcdonald Islands" = "HMD",
  "Holy See Vatican City State" = "VAT",
  Honduras = "HND",
  HongKong = "HKG",
  Hungary = "HUN",
  Iceland = "ISL",
  India = "IND",
  Indonesia = "IDN",
  Iran = "IRN",
  Iraq = "IRQ",
  Ireland = "IRL",
  "Isle Of Man" = "IMN",
  Israel = "ISR",
  Italy = "ITA",
  Jamaica = "JAM",
  Japan = "JPN",
  Jersey = "JEY",
  Jordan = "JOR",
  Kazakhstan = "KAZ",
  Kenya = "KEN",
  Kiribati = "KIR",
  "Korea, Republic of" = "KOR",
  "Korea, Democratic People's Republic of" = "PRK",
  Kuwait = "KWT",
  Kyrgyzstan = "KGZ",
  "Lao Peoples Democratic Republic" = "LAO",
  Latvia = "LVA",
  Lebanon = "LBN",
  Lesotho = "LSO",
  Liberia = "LBR",
  "Libyan Arab Jamahiriya" = "LBY",
  Liechtenstein = "LIE",
  Lithuania = "LTU",
  Luxembourg = "LUX",
  Macao = "MAC",
  Madagascar = "MDG",
  Malawi = "MWI",
  Malaysia = "MYS",
  Maldives = "MDV",
  Mali = "MLI",
  Malta = "MLT",
  "Marshall Islands" = "MHL",
  Martinique = "MTQ",
  Mauritania = "MRT",
  Mauritius = "MUS",
  Mayotte = "MYT",
  Mexico = "MEX",
  Micronesia = "FSM",
  Moldova = "MDA",
  Monaco = "MCO",
  Mongolia = "MNG",
  Montenegro = "MNE",
  Montserrat = "MSR",
  Morocco = "MAR",
  Mozambique = "MOZ",
  Myanmar = "MMR",
  Namibia = "NAM",
  Nauru = "NRU",
  Nepal = "NPL",
  Netherlands = "NLD",
  "New Caledonia" = "NCL",
  "New Zealand" = "NZL",
  Nicaragua = "NIC",
  Niger = "NER",
  Nigeria = "NGA",
  Niue = "NIU",
  "Norfolk Island" = "NFK",
  "Northern Mariana Islands" = "MNP",
  Norway = "NOR",
  Oman = "OMN",
  Pakistan = "PAK",
  Palau = "PLW",
  "Palestinian Territory" = "PSE",
  Panama = "PAN",
  "Papua New Guinea" = "PNG",
  Paraguay = "PRY",
  Peru = "PER",
  Philippines = "PHL",
  Pitcairn = "PCN",
  Poland = "POL",
  Portugal = "PRT",
  "Puerto Rico" = "PRI",
  Qatar = "QAT",
  "Republic of North Macedonia" = "MKD",
  "Réunion" = "REU",
  Romania = "ROU",
  "Russian Federation" = "RUS",
  Rwanda = "RWA",
  "Saint Barthelemy" = "BLM",
  "Saint Helena" = "SHN",
  "Saint Kitts And Nevis" = "KNA",
  "Saint Lucia" = "LCA",
  "Saint Martin" = "MAF",
  "Saint Pierre And Miquelon" = "SPM",
  "Saint Vincent And Grenadines" = "VCT",
  Samoa = "WSM",
  "San Marino" = "SMR",
  "Sao Tome And Principe" = "STP",
  "Saudi Arabia" = "SAU",
  Senegal = "SEN",
  Serbia = "SRB",
  Seychelles = "SYC",
  "Sierra Leone" = "SLE",
  Singapore = "SGP",
  "Sint Maarten (Dutch part)" = "SXM",
  Slovakia = "SVK",
  Slovenia = "SVN",
  "Solomon Islands" = "SLB",
  Somalia = "SOM",
  "South Africa" = "ZAF",
  "South Georgia And Sandwich Island" = "SGS",
  "South Sudan" = "SSD",
  Spain = "ESP",
  "Sri Lanka" = "LKA",
  Sudan = "SDN",
  Suriname = "SUR",
  "Svalbard And Jan Mayen" = "SJM",
  Swaziland = "SWZ",
  Sweden = "SWE",
  Switzerland = "CHE",
  "Syrian Arab Republic" = "SYR",
  Taiwan = "TWN",
  Tajikistan = "TJK",
  Tanzania = "TZA",
  Thailand = "THA",
  "Timor-Leste" = "TLS",
  Togo = "TGO",
  Tokelau = "TKL",
  Tonga = "TON",
  "Trinidad And Tobago" = "TTO",
  Tunisia = "TUN",
  Turkey = "TUR",
  Turkmenistan = "TKM",
  "Turks And Caicos Islands" = "TCA",
  Tuvalu = "TUV",
  Uganda = "UGA",
  Ukraine = "UKR",
  "United Arab Emirates" = "ARE",
  "United Kingdom" = "GBR",
  "United States Outlying Islands" = "UMI",
  "United States" = "USA",
  Uruguay = "URY",
  Uzbekistan = "UZB",
  Vanuatu = "VUT",
  Venezuela = "VEN",
  Vietnam = "VNM",
  "Virgin Islands British" = "VGB",
  "Virgin Islands US" = "VIR",
  "Wallis And Futuna" = "WLF",
  "Western Sahara" = "ESH",
  Yemen = "YEM",
  Zambia = "ZMB",
  "Zimbabwe" = "ZWE",
}

export interface Position {
  longitude: number;
  latitude: number;
}

export interface BoundingBox {
  longitudeSW: number;
  latitudeSW: number;
  longitudeNE: number;
  latitudeNE: number;
}

export interface PlacesGeocoderOptions {
  enableAll?: boolean;
  enableGetSuggestions?: boolean;
  enableSearchByPlaceId?: boolean;
  omitSuggestionsWithoutPlaceId?: boolean;
  searchByPlaceIdAdditionalFeatures?: GetPlaceAdditionalFeature[];
  reverseGeocodeAdditionalFeatures?: ReverseGeocodeAdditionalFeature[];
  forwardGeocodeAdditionalFeatures?: SearchTextAdditionalFeature[];
  placeholder?: string;
  placesIndex?: string;
  flyTo?: boolean | FlyToOptions;
  zoom?: number;
  trackProximity?: boolean;
  proximityMinZoom?: number;
  minLength?: number;
  reverseGeocode?: boolean;
  limit?: number;
  collapsed?: boolean;
  clearAndBlurOnEsc?: boolean;
  clearOnBlur?: boolean;
  localGeocoderOnly?: boolean;
  debounceSearch?: number;
  language?: string;
  reverseMode?: "distance" | "score";
  getItemValue?: (item: CarmenGeojsonFeature) => string;
  render?: (item: CarmenGeojsonFeature) => string;
  popupRender?: (item: CarmenGeojsonFeature) => string;
  filter?: (item: CarmenGeojsonFeature) => boolean;
}

export interface FlyToOptions {
  speed?: number;
  zoom?: number;
  curve?: number;
  minZoom?: number;
  screenSpeed?: number;
  maxDuration?: number;
}

export interface CarmenGeojsonFeature {
  bbox?: [number, number, number, number];
  id: string;
  language?: string;
  place_name: string;
  place_type: string[];
  text: string;
}
